export const STATIONS = [
  {
    name: "New Delhi",
    code: "NDLS",
    tagline: "City of Empires",
    cards: [
      {
        title: "Boarding At New Delhi",
        desc: "boarding at new delhi",
        tag: "Journey starts",
        img: "https://images.unsplash.com/photo-1587474260584-136574528ed5",
      },
    ],
  },

  {
    name: "Jaipur",
    code: "JP",
    tagline: "The Pink City",
    cards: [
      {
        title: "Hawa Mahal",
        desc: "Palace of the breeze",
        tag: "Iconic",
        img: "https://lh3.googleusercontent.com/gps-cs-s/AHVAwepWJKu_T90FqAZxWYq1epOxtZ5RaFBozhhTrWZsWt7eddNYs4o6ZbqzergvZyNMT1HzaX4Qht3tIKk_gB_VAB_mYRqWwoBelIpoXxq8UZ5jOsBAbPT_wRdLedQPAx1OJiaIzcmWFg=s1360-w1360-h1020-rw",
      },
      {
        title: "Amber Fort",
        desc: "Rajput glory on a ridge",
        tag: "Heritage",
        img: "https://www.swantour.com/blogs/wp-content/uploads/2018/09/Amer-Fort.jpg",
      },
      {
        title: "City Palace",
        desc: "Royal residence still alive",
        tag: "Royal",
        img: "https://images.unsplash.com/photo-1609947017136-9daf32a5eb16",
      },
      {
        title: "Jantar Mantar",
        desc: "Celestial instruments in stone",
        tag: "UNESCO",
        img: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09c",
      },
      {
        title: "Nahargarh Fort",
        desc: "Sunset vistas over the city",
        tag: "Vista",
        img: "https://images.unsplash.com/photo-1629893379834-4b1b02f3c7dc",
      },
      {
        title: "Jal Mahal",
        desc: "Water palace at dusk",
        tag: "Romance",
        img: "https://images.unsplash.com/photo-1609947017136-9daf32a5eb16",
      },
      {
        title: "Albert Hall",
        desc: "Indo-Saracenic masterpiece",
        tag: "Museum",
        img: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09c",
      },
    ],
  },

  {
    name: "Sawai Madhupur",
    code: "SWM",
    tagline: "Gateway to the Wild",
    cards: [
      {
        title: "Ranthambore",
        desc: "Tigers in ancient ruins",
        tag: "Safari",
        img: "https://images.unsplash.com/photo-1552410260-0fd9b577afa6",
      },
      {
        title: "Ranthambore Fort",
        desc: "10th-century citadel",
        tag: "Heritage",
        img: "https://images.unsplash.com/photo-1587474260584-136574528ed5",
      },
      {
        title: "Padam Talao",
        desc: "Largest lake in the park",
        tag: "Nature",
        img: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
      },
      {
        title: "Jogi Mahal",
        desc: "Forest lodge at the lake",
        tag: "Retreat",
        img: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
      },
      {
        title: "Trinetra Ganesh",
        desc: "Sacred temple in the fort",
        tag: "Spiritual",
        img: "https://images.unsplash.com/photo-1587474260584-136574528ed5",
      },
      {
        title: "Kachida Valley",
        desc: "Leopard and sloth bear country",
        tag: "Wildlife",
        img: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
      },
      {
        title: "Raj Bagh Ruins",
        desc: "Crumbling palace and crocodiles",
        tag: "Ruins",
        img: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09c",
      },
      {
        title: "Zone 3 & 4",
        desc: "Prime big-cat territory",
        tag: "Safari",
        img: "https://images.unsplash.com/photo-1552410260-0fd9b577afa6",
      },
    ],
  },

  {
    name: "Udaipur",
    code: "UDZ",
    tagline: "Venice of the East",
    cards: [
      {
        title: "City Palace",
        desc: "Marble and mirror on the lake",
        tag: "Royal",
        img: "https://images.unsplash.com/photo-1589308078059-be1415eab4c3",
      },
      {
        title: "Lake Pichola",
        desc: "Shimmering heart of the city",
        tag: "Scenic",
        img: "https://images.unsplash.com/photo-1599661046289-e31897846e41",
      },
      {
        title: "Jag Mandir",
        desc: "Island palace of exile",
        tag: "History",
        img: "https://images.unsplash.com/photo-1589308078059-be1415eab4c3",
      },
      {
        title: "Saheliyon-ki-Bari",
        desc: "Garden of the Maidens",
        tag: "Garden",
        img: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
      },
      {
        title: "Bagore-ki-Haveli",
        desc: "Mewar cultural evening",
        tag: "Culture",
        img: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09c",
      },
      {
        title: "Fateh Sagar Lake",
        desc: "Western lake at golden hour",
        tag: "Sunset",
        img: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
      },
      {
        title: "Eklingji Temple",
        desc: "Lord Shiva's royal seat",
        tag: "Spiritual",
        img: "https://images.unsplash.com/photo-1587474260584-136574528ed5",
      },
      {
        title: "Sajjangarh",
        desc: "Monsoon Palace on the hill",
        tag: "Vista",
        img: "https://images.unsplash.com/photo-1629893379834-4b1b02f3c7dc",
      },
    ],
  },

  {
    name: "Jaisalmer",
    code: "JSM",
    tagline: "The Golden City",
    cards: [
      {
        title: "Jaisalmer Fort",
        desc: "Living fort of golden sandstone",
        tag: "UNESCO",
        img: "https://images.unsplash.com/photo-1589308078059-be1415eab4c3",
      },
      {
        title: "Sam Sand Dunes",
        desc: "Camel rides at sunset",
        tag: "Desert",
        img: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
      },
      {
        title: "Patwon-ki-Haveli",
        desc: "Filigree facades in gold",
        tag: "Heritage",
        img: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09c",
      },
      {
        title: "Gadisar Lake",
        desc: "Migratory birds at dawn",
        tag: "Nature",
        img: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
      },
      {
        title: "Desert Camp",
        desc: "Stars above the Thar",
        tag: "Experience",
        img: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
      },
      {
        title: "Salim Singh Haveli",
        desc: "Peacock arch mansion",
        tag: "Architecture",
        img: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09c",
      },
      {
        title: "Bada Bagh",
        desc: "Royal cenotaphs in the dunes",
        tag: "Regal",
        img: "https://images.unsplash.com/photo-1629893379834-4b1b02f3c7dc",
      },
      {
        title: "Kuldhara Village",
        desc: "Haunted, abandoned hamlet",
        tag: "Mystery",
        img: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
      },
    ],
  },

  {
    name: "Jodhpur",
    code: "JU",
    tagline: "The Blue City",
    cards: [
      {
        title: "Mehrangarh Fort",
        desc: "Towering above blue rooftops",
        tag: "Majestic",
        img: "https://images.unsplash.com/photo-1609947017136-9daf32a5eb16",
      },
      {
        title: "Umaid Bhawan",
        desc: "Art Deco palace hotel",
        tag: "Luxury",
        img: "https://images.unsplash.com/photo-1589308078059-be1415eab4c3",
      },
      {
        title: "Jaswant Thada",
        desc: "Marble cenotaph aglow",
        tag: "Heritage",
        img: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09c",
      },
      {
        title: "Clock Tower",
        desc: "Bazaar life below the spire",
        tag: "Market",
        img: "https://images.unsplash.com/photo-1599661046289-e31897846e41",
      },
      {
        title: "Mandore Gardens",
        desc: "Ruins and cenotaphs at dusk",
        tag: "Garden",
        img: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
      },
      {
        title: "Sardar Market",
        desc: "Handicrafts and textiles",
        tag: "Shopping",
        img: "https://images.unsplash.com/photo-1599661046289-e31897846e41",
      },
      {
        title: "Blue City Walk",
        desc: "Cobalt lanes of Brahmpuri",
        tag: "Culture",
        img: "https://images.unsplash.com/photo-1609947017136-9daf32a5eb16",
      },
      {
        title: "Balsamand Lake",
        desc: "9th century reservoir",
        tag: "Scenic",
        img: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
      },
    ],
  },

  {
    name: "Agra",
    code: "AGC",
    tagline: "The City of the Taj",
    cards: [
      {
        title: "Taj Mahal",
        desc: "Love in white marble",
        tag: "UNESCO",
        img: "https://images.unsplash.com/photo-1564507592333-c60657eea523",
      },
      {
        title: "Agra Fort",
        desc: "Red sandstone Mughal citadel",
        tag: "Heritage",
        img: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09c",
      },
      {
        title: "Fatehpur Sikri",
        desc: "Abandoned capital in stone",
        tag: "UNESCO",
        img: "https://images.unsplash.com/photo-1587474260584-136574528ed5",
      },
      {
        title: "Mehtab Bagh",
        desc: "Moonlight garden across the river",
        tag: "Scenic",
        img: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
      },
      {
        title: "Itmad-ud-Daula",
        desc: "Baby Taj—first marble mausoleum",
        tag: "Mughal",
        img: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09c",
      },
      {
        title: "Kinari Bazaar",
        desc: "Marble inlay and brasswork",
        tag: "Market",
        img: "https://images.unsplash.com/photo-1599661046289-e31897846e41",
      },
      {
        title: "Jama Masjid",
        desc: "Shah Jahan's mosque",
        tag: "Spiritual",
        img: "https://images.unsplash.com/photo-1587474260584-136574528ed5",
      },
      {
        title: "Chini-ka-Rauza",
        desc: "Persian tile masterpiece",
        tag: "Architecture",
        img: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09c",
      },
    ],
  },
  {
    name: "New Delhi",
    code: "NDLS",
    tagline: "City of Empires",
    cards: [
      {
        title: "Boarding At New Delhi",
        desc: "boarding at new delhi",
        tag: "Journey starts",
        img: "https://images.unsplash.com/photo-1587474260584-136574528ed5",
      },
    ],
  },
];

export const TAG_COLORS: Record<string, string> = {
  Heritage: "#c9a84c",
  UNESCO: "#e8a045",
  Mughal: "#b87333",
  Landmark: "#8fbc8f",
  Garden: "#6b8f71",
  Market: "#d4956a",
  Spiritual: "#9b7db6",
  Culture: "#c17f7f",
  Royal: "#c9a84c",
  Iconic: "#e8a045",
  Vista: "#6aafb8",
  Romance: "#c17f7f",
  Museum: "#8fbc8f",
  Safari: "#7a9e5c",
  Nature: "#6b8f71",
  Retreat: "#9b7db6",
  Wildlife: "#7a9e5c",
  Ruins: "#b87333",
  Scenic: "#6aafb8",
  History: "#b87333",
  Sunset: "#e8a045",
  Desert: "#c9a84c",
  Experience: "#d4956a",
  Architecture: "#b87333",
  Regal: "#c9a84c",
  Mystery: "#9b7db6",
  Luxury: "#c9a84c",
  Majestic: "#c9a84c",
  Shopping: "#d4956a",
};